name: hotel_project

include:
  - docker/apps/nacos.yml
  - docker/apps/hotel-frontend.yml
  - docker/apps/hotel-backend.yml
  - docker/infra/oracle.yml
  - docker/infra/redis.yml
  - docker/tools/ops-tools.yml
