spring:
  datasource:
    # 开发环境：连接映射到宿主机的端口 (localhost)
    url: jdbc:oracle:thin:@hotel-oracle:1521/FREEPDB1
  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - redis-sentinel1:26379
          - redis-sentinel2:26379
          - redis-sentinel3:26379

jetcache:
  remote:
    default:
      # 增加 readFrom=REPLICA_PREFERRED 参数启用 JetCache 的读写分离
      uri: redis-sentinel://redis-sentinel1:26379,redis-sentinel2:26379,redis-sentinel3:26379?sentinelMasterId=mymaster&readFrom=REPLICA_PREFERRED
