FROM node:20-alpine

WORKDIR /frontend
ARG NPM_REGISTRY=https://registry.npmmirror.com

# 拷贝依赖配置并下载依赖
COPY hotel-frontend/package*.json ./
RUN --mount=type=cache,target=/frontend/.npm \
	npm config set registry ${NPM_REGISTRY} \
	&& npm ci --cache /frontend/.npm --prefer-offline --ignore-scripts

EXPOSE 3000
CMD ["npm", "start"]
