services:
  backend:
    build:
      context: ../../
      dockerfile: docker/apps/Dockerfile.dev.backend
    container_name: hotel-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: oracle
      DB_PORT: 1521
      DB_SERVICE: FREEPDB1
      DB_USERNAME: ${ORACLE_APP_USER:-system}
      DB_PASSWORD: ${ORACLE_APP_USER_PASSWORD:-Hotel_PWD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_BUCKET: ${MINIO_BUCKET:-hotel-files}
      NACOS_SERVER_ADDR: nacos:8848
      SPRING_CLOUD_NACOS_SERVER_ADDR: nacos:8848
      SENTINEL_DASHBOARD_ADDR: sentinel-dashboard:8858
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
    depends_on:
      oracle:
        condition: service_healthy
      redis-master:
        condition: service_started
      nacos:
        condition: service_started
      sentinel-dashboard:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ../../hotel-backend/src:/app/src
      - ../../hotel-backend/target/classes:/app/target/classes
      - ../../hotel-backend/pom.xml:/app/pom.xml
      - ./maven-repo:/root/.m2/repository
    x-develop:
      watch:
        - path: ../../hotel-backend/target/classes
          action: sync
          target: /app/target/classes
